-- Generated by Willowsoft.WillowLib.CodeGen.TableCreator at 3/7/2009 5:09:16 PM
-- Drop tables and roles

DROP TABLE dbo.PurLine
DROP TABLE dbo.PurOrder
DROP TABLE dbo.VendorProduct
DROP TABLE dbo.Product
DROP TABLE dbo.ProductBrand
DROP TABLE dbo.ProductSubCategory
DROP TABLE dbo.ProductCategory
DROP TABLE dbo.Vendor
DROP TABLE dbo.Contact

DROP ROLE Programs

GO

-- Create tables and roles

CREATE ROLE Programs

CREATE TABLE dbo.Contact
(
    ContactId int IDENTITY(1,1) NOT NULL
    ,FirstName varchar(60) NOT NULL
    ,Initial varchar(1) NOT NULL
    ,LastName varchar(60) NOT NULL
    ,Street1 varchar(60) NOT NULL
    ,Street2 varchar(60) NOT NULL
    ,City varchar(60) NOT NULL
    ,StateProvince varchar(10) NOT NULL
    ,PostalCode varchar(12) NOT NULL
    ,Country varchar(10) NOT NULL
    ,PhoneNumber varchar(25) NOT NULL
    ,CellNumber varchar(25) NOT NULL
    ,FaxNumber varchar(25) NOT NULL
    ,EmailAddress varchar(60) NOT NULL
    ,Notes varchar(2048) NOT NULL
    ,IsActive tinyint NOT NULL
    ,CreateDate smalldatetime NOT NULL
    ,ModifyDate smalldatetime NOT NULL
    ,CONSTRAINT pkContact PRIMARY KEY (ContactId)
    ,CONSTRAINT ckContact_Names CHECK (LEN(LastName)>0 AND LEN(FirstName)>0)
)

CREATE UNIQUE INDEX ContactIdx_Names ON dbo.Contact(LastName, FirstName)
CREATE INDEX ContactIdx_PhoneNumber ON dbo.Contact(PhoneNumber)
CREATE INDEX ContactIdx_CellNumber ON dbo.Contact(CellNumber)
CREATE INDEX ContactIdx_FaxNumber ON dbo.Contact(FaxNumber)
CREATE INDEX ContactIdx_Email ON dbo.Contact(EmailAddress)

CREATE TABLE dbo.Vendor
(
    VendorId int IDENTITY(1,1) NOT NULL
    ,VendorName varchar(100) NOT NULL
    ,Terms varchar(20) NOT NULL
    ,PriceCode int NOT NULL
    ,Shipping varchar(50) NOT NULL
    ,SortCode varchar(6) NOT NULL
    ,RepContactId int NULL
    ,OrdContactId int NULL
    ,ShpContactId int NULL
    ,ActContactId int NULL
    ,Notes varchar(2048) NOT NULL
    ,PreferredVendor tinyint NOT NULL
    ,IsActive tinyint NOT NULL
    ,PricingRequiresReview tinyint NOT NULL
    ,CreateDate smalldatetime NOT NULL
    ,ModifyDate smalldatetime NOT NULL
    ,CONSTRAINT pkVendor PRIMARY KEY (VendorId)
    ,CONSTRAINT ckVendor_Name CHECK (LEN(VendorName)>0)
    ,CONSTRAINT fkVendor_RepContact FOREIGN KEY (RepContactID) REFERENCES dbo.Contact(ContactId)
    ,CONSTRAINT fkVendor_OrdContact FOREIGN KEY (OrdContactID) REFERENCES dbo.Contact(ContactId)
    ,CONSTRAINT fkVendor_ShpContact FOREIGN KEY (ShpContactID) REFERENCES dbo.Contact(ContactId)
    ,CONSTRAINT fkVendor_ActContact FOREIGN KEY (ActContactID) REFERENCES dbo.Contact(ContactId)
)

CREATE UNIQUE INDEX VendorIdx_VendorName ON dbo.Vendor(VendorName)

CREATE TABLE dbo.ProductCategory
(
    ProductCategoryId int IDENTITY(1,1) NOT NULL
    ,CategoryName varchar(40) NOT NULL
    ,SortCode varchar(4) NOT NULL
    ,Notes varchar(2048) NOT NULL
    ,IsActive tinyint NOT NULL
    ,CreateDate smalldatetime NOT NULL
    ,ModifyDate smalldatetime NOT NULL
    ,CONSTRAINT pkProductCategory PRIMARY KEY (ProductCategoryId)
    ,CONSTRAINT ckProductCategory_Name CHECK (LEN(CategoryName)>0)
    ,CONSTRAINT ckProductCategory_Sort CHECK (LEN(SortCode)>0)
)

CREATE UNIQUE INDEX ProductCategoryIdx_Name ON dbo.ProductCategory(CategoryName)
CREATE INDEX ProductCategoryIdx_Sort ON dbo.ProductCategory(SortCode)

CREATE TABLE dbo.ProductSubCategory
(
    ProductSubCategoryId int IDENTITY(1,1) NOT NULL
    ,SubCategoryName varchar(40) NOT NULL
    ,SortCode varchar(6) NOT NULL
    ,ProductCategoryId int NOT NULL
    ,DefaultProfitMargin int NOT NULL
    ,Notes varchar(2048) NOT NULL
    ,IsActive tinyint NOT NULL
    ,PricingRequiresReview tinyint NOT NULL
    ,CreateDate smalldatetime NOT NULL
    ,ModifyDate smalldatetime NOT NULL
    ,CONSTRAINT pkProductSubCategory PRIMARY KEY (ProductSubCategoryId)
    ,CONSTRAINT ckProductSubCategory_Name CHECK (LEN(SubCategoryName)>0)
    ,CONSTRAINT ckProductSubCategory_Sort CHECK (LEN(SortCode)>0)
    ,CONSTRAINT fkProductSubCategory_Category FOREIGN KEY (ProductCategoryId) REFERENCES dbo.ProductCategory(ProductCategoryId)
)

CREATE UNIQUE INDEX ProductSubCategoryIdx_Name ON dbo.ProductSubCategory(SubCategoryName)
CREATE INDEX ProductSubCategoryIdx_Sort ON dbo.ProductSubCategory(SortCode)

CREATE TABLE dbo.ProductBrand
(
    ProductBrandId int IDENTITY(1,1) NOT NULL
    ,BrandName varchar(80) NOT NULL
    ,Notes varchar(2048) NOT NULL
    ,IsActive tinyint NOT NULL
    ,CreateDate smalldatetime NOT NULL
    ,ModifyDate smalldatetime NOT NULL
    ,CONSTRAINT pkProductBrand PRIMARY KEY (ProductBrandId)
    ,CONSTRAINT ckProductBrand_Name CHECK (LEN(BrandName)>0)
)

CREATE UNIQUE INDEX ProductBrandIdx_Name ON dbo.ProductBrand(BrandName)

CREATE TABLE dbo.Product
(
    ProductId int IDENTITY(1,1) NOT NULL
    ,ProductName varchar(100) NOT NULL
    ,ProductSubCategoryId int NOT NULL
    ,Size varchar(30) NOT NULL
    ,RetailPrice money NOT NULL
    ,ProductBrandId int NOT NULL
    ,ManufacturerBarcode varchar(30) NOT NULL
    ,ManufacturerPartNum varchar(30) NOT NULL
    ,IsActive tinyint NOT NULL
    ,PricingRequiresReview tinyint NOT NULL
    ,CreateDate smalldatetime NOT NULL
    ,ModifyDate smalldatetime NOT NULL
    ,CONSTRAINT pkProduct PRIMARY KEY (ProductId)
    ,CONSTRAINT ckProduct_Name CHECK (LEN(ProductName)>0)
    ,CONSTRAINT fkProduct_SubCat FOREIGN KEY (ProductSubCategoryId) REFERENCES dbo.ProductSubCategory(ProductSubCategoryId)
    ,CONSTRAINT fkProduct_Brand FOREIGN KEY (ProductBrandId) REFERENCES dbo.ProductBrand(ProductBrandId)
)

CREATE INDEX Product_SubCat ON dbo.Product(ProductSubCategoryId, ProductName)
CREATE INDEX Product_Barcode ON dbo.Product(ManufacturerBarcode)
CREATE INDEX Product_PartNum ON dbo.Product(ManufacturerPartNum)
CREATE UNIQUE INDEX Product_Brand ON dbo.Product(ProductBrandId, ProductName, Size)

CREATE TABLE dbo.VendorProduct
(
    VendorProductId int IDENTITY(1,1) NOT NULL
    ,VendorId int NOT NULL
    ,ProductId int NOT NULL
    ,RetailPriceOverride money NOT NULL
    ,VendorPartNum varchar(30) NOT NULL
    ,CaseCost money NOT NULL
    ,CountInCase int NOT NULL
    ,EachCost money NOT NULL
    ,PreferredSource tinyint NOT NULL
    ,IsActive tinyint NOT NULL
    ,PricingRequiresReview tinyint NOT NULL
    ,NumAndCostRequireReview tinyint NOT NULL
    ,CreateDate smalldatetime NOT NULL
    ,ModifyDate smalldatetime NOT NULL
    ,CONSTRAINT pkVendorProduct PRIMARY KEY (VendorProductId)
    ,CONSTRAINT fkVendorProduct_Vendor FOREIGN KEY (VendorId) REFERENCES dbo.Vendor(VendorId)
    ,CONSTRAINT fkVendorProduct_Product FOREIGN KEY (ProductId) REFERENCES dbo.Product(ProductId)
)

CREATE UNIQUE INDEX VendorProduct_Vendor ON dbo.VendorProduct(VendorId, VendorPartNum)
CREATE INDEX VendorProduct_Product ON dbo.VendorProduct(ProductId)
CREATE INDEX Product_PartNum ON dbo.VendorProduct(VendorPartNum)

CREATE TABLE dbo.PurOrder
(
    PurOrderId int IDENTITY(1,1) NOT NULL
    ,VendorId int NOT NULL
    ,OrderNumber varchar(12) NOT NULL
    ,OrderDate smalldatetime NOT NULL
    ,ShipDate smalldatetime NULL
    ,SubmitDate smalldatetime NULL
    ,CreatedBy varchar(20) NOT NULL
    ,Discount int NOT NULL
    ,InvoiceNumber varchar(12) NOT NULL
    ,Freight money NOT NULL
    ,Terms varchar(20) NOT NULL
    ,Notes varchar(2048) NOT NULL
    ,CreateDate smalldatetime NOT NULL
    ,ModifyDate smalldatetime NOT NULL
    ,CONSTRAINT pkPurOrder PRIMARY KEY (PurOrderId)
    ,CONSTRAINT fkPurOrder_Vendor FOREIGN KEY (VendorId) REFERENCES dbo.Vendor(VendorId)
)

CREATE INDEX PurOrder_Vendor ON dbo.PurOrder(VendorId)
CREATE INDEX PurOrder_Date ON dbo.PurOrder(OrderDate)

CREATE TABLE dbo.PurLine
(
    PurLineId int IDENTITY(1,1) NOT NULL
    ,PurOrderId int NOT NULL
    ,VendorProductId int NOT NULL
    ,CaseCostOverride money NOT NULL
    ,EachCostOverride money NOT NULL
    ,OrderedEaches tinyint NOT NULL
    ,QtyOrdered int NOT NULL
    ,QtyReceived int NOT NULL
    ,QtyBackordered int NOT NULL
    ,QtyDamaged int NOT NULL
    ,QtyMissing int NOT NULL
    ,QtyOnHand int NOT NULL
    ,Notes varchar(80) NOT NULL
    ,CreateDate smalldatetime NOT NULL
    ,ModifyDate smalldatetime NOT NULL
    ,CONSTRAINT pkPurLine PRIMARY KEY (PurLineId)
    ,CONSTRAINT fkPurLine_PurOrder FOREIGN KEY (PurOrderId) REFERENCES dbo.PurOrder(PurOrderId)
    ,CONSTRAINT fkPurLine_VendorProduct FOREIGN KEY (VendorProductId) REFERENCES dbo.VendorProduct(VendorProductId)
)

CREATE INDEX PurLine_PurOrder ON dbo.PurLine(PurOrderId)

GO

