-- Generated by Willowsoft.WillowLib.CodeGen.StoredProcCreator at 3/7/2009 5:10:28 PM

-- Contact Stored Procedures

DROP PROC dbo.GetContact
DROP PROC dbo.InsertContact
DROP PROC dbo.UpdateContact
DROP PROC dbo.DeleteContact

GO

---------------

CREATE PROC dbo.GetContact
  @ContactId int
AS

SELECT *
FROM   Contact
WHERE  ContactId=@ContactId

GO

GRANT EXECUTE ON dbo.GetContact TO Programs

GO

---------------

CREATE PROC dbo.InsertContact
    @ContactId int out
    ,@FirstName varchar(60)
    ,@Initial varchar(1)
    ,@LastName varchar(60)
    ,@Street1 varchar(60)
    ,@Street2 varchar(60)
    ,@City varchar(60)
    ,@StateProvince varchar(10)
    ,@PostalCode varchar(12)
    ,@Country varchar(10)
    ,@PhoneNumber varchar(25)
    ,@CellNumber varchar(25)
    ,@FaxNumber varchar(25)
    ,@EmailAddress varchar(60)
    ,@Notes varchar(2048)
    ,@IsActive tinyint
AS

INSERT Contact (FirstName
    ,Initial
    ,LastName
    ,Street1
    ,Street2
    ,City
    ,StateProvince
    ,PostalCode
    ,Country
    ,PhoneNumber
    ,CellNumber
    ,FaxNumber
    ,EmailAddress
    ,Notes
    ,IsActive
    ,CreateDate, ModifyDate)
VALUES(@FirstName
    ,@Initial
    ,@LastName
    ,@Street1
    ,@Street2
    ,@City
    ,@StateProvince
    ,@PostalCode
    ,@Country
    ,@PhoneNumber
    ,@CellNumber
    ,@FaxNumber
    ,@EmailAddress
    ,@Notes
    ,@IsActive
    ,GETDATE(),GETDATE())

SELECT @ContactId=@@IDENTITY

GO

GRANT EXECUTE ON dbo.InsertContact TO Programs

GO

---------------

CREATE PROC dbo.UpdateContact
    @ContactId int
    ,@FirstName varchar(60)
    ,@Initial varchar(1)
    ,@LastName varchar(60)
    ,@Street1 varchar(60)
    ,@Street2 varchar(60)
    ,@City varchar(60)
    ,@StateProvince varchar(10)
    ,@PostalCode varchar(12)
    ,@Country varchar(10)
    ,@PhoneNumber varchar(25)
    ,@CellNumber varchar(25)
    ,@FaxNumber varchar(25)
    ,@EmailAddress varchar(60)
    ,@Notes varchar(2048)
    ,@IsActive tinyint
AS

UPDATE Contact
    SET FirstName=@FirstName
    ,Initial=@Initial
    ,LastName=@LastName
    ,Street1=@Street1
    ,Street2=@Street2
    ,City=@City
    ,StateProvince=@StateProvince
    ,PostalCode=@PostalCode
    ,Country=@Country
    ,PhoneNumber=@PhoneNumber
    ,CellNumber=@CellNumber
    ,FaxNumber=@FaxNumber
    ,EmailAddress=@EmailAddress
    ,Notes=@Notes
    ,IsActive=@IsActive
    ,ModifyDate=GETDATE()
WHERE ContactId=@ContactId

GO

GRANT EXECUTE ON dbo.UpdateContact TO Programs

GO

---------------

CREATE PROC dbo.DeleteContact
  @ContactId int
AS

DELETE Contact
WHERE  ContactId=@ContactId

GO

GRANT EXECUTE ON dbo.DeleteContact TO Programs

GO

-- Vendor Stored Procedures

DROP PROC dbo.GetVendor
DROP PROC dbo.InsertVendor
DROP PROC dbo.UpdateVendor
DROP PROC dbo.DeleteVendor

GO

---------------

CREATE PROC dbo.GetVendor
  @VendorId int
AS

SELECT *
FROM   Vendor
WHERE  VendorId=@VendorId

GO

GRANT EXECUTE ON dbo.GetVendor TO Programs

GO

---------------

CREATE PROC dbo.InsertVendor
    @VendorId int out
    ,@VendorName varchar(100)
    ,@Terms varchar(20)
    ,@PriceCode int
    ,@Shipping varchar(50)
    ,@SortCode varchar(6)
    ,@RepContactId int
    ,@OrdContactId int
    ,@ShpContactId int
    ,@ActContactId int
    ,@Notes varchar(2048)
    ,@PreferredVendor tinyint
    ,@IsActive tinyint
    ,@PricingRequiresReview tinyint
AS

INSERT Vendor (VendorName
    ,Terms
    ,PriceCode
    ,Shipping
    ,SortCode
    ,RepContactId
    ,OrdContactId
    ,ShpContactId
    ,ActContactId
    ,Notes
    ,PreferredVendor
    ,IsActive
    ,PricingRequiresReview
    ,CreateDate, ModifyDate)
VALUES(@VendorName
    ,@Terms
    ,@PriceCode
    ,@Shipping
    ,@SortCode
    ,@RepContactId
    ,@OrdContactId
    ,@ShpContactId
    ,@ActContactId
    ,@Notes
    ,@PreferredVendor
    ,@IsActive
    ,@PricingRequiresReview
    ,GETDATE(),GETDATE())

SELECT @VendorId=@@IDENTITY

GO

GRANT EXECUTE ON dbo.InsertVendor TO Programs

GO

---------------

CREATE PROC dbo.UpdateVendor
    @VendorId int
    ,@VendorName varchar(100)
    ,@Terms varchar(20)
    ,@PriceCode int
    ,@Shipping varchar(50)
    ,@SortCode varchar(6)
    ,@RepContactId int
    ,@OrdContactId int
    ,@ShpContactId int
    ,@ActContactId int
    ,@Notes varchar(2048)
    ,@PreferredVendor tinyint
    ,@IsActive tinyint
    ,@PricingRequiresReview tinyint
AS

UPDATE Vendor
    SET VendorName=@VendorName
    ,Terms=@Terms
    ,PriceCode=@PriceCode
    ,Shipping=@Shipping
    ,SortCode=@SortCode
    ,RepContactId=@RepContactId
    ,OrdContactId=@OrdContactId
    ,ShpContactId=@ShpContactId
    ,ActContactId=@ActContactId
    ,Notes=@Notes
    ,PreferredVendor=@PreferredVendor
    ,IsActive=@IsActive
    ,PricingRequiresReview=@PricingRequiresReview
    ,ModifyDate=GETDATE()
WHERE VendorId=@VendorId

GO

GRANT EXECUTE ON dbo.UpdateVendor TO Programs

GO

---------------

CREATE PROC dbo.DeleteVendor
  @VendorId int
AS

DELETE Vendor
WHERE  VendorId=@VendorId

GO

GRANT EXECUTE ON dbo.DeleteVendor TO Programs

GO

-- ProductCategory Stored Procedures

DROP PROC dbo.GetProductCategory
DROP PROC dbo.InsertProductCategory
DROP PROC dbo.UpdateProductCategory
DROP PROC dbo.DeleteProductCategory

GO

---------------

CREATE PROC dbo.GetProductCategory
  @ProductCategoryId int
AS

SELECT *
FROM   ProductCategory
WHERE  ProductCategoryId=@ProductCategoryId

GO

GRANT EXECUTE ON dbo.GetProductCategory TO Programs

GO

---------------

CREATE PROC dbo.InsertProductCategory
    @ProductCategoryId int out
    ,@CategoryName varchar(40)
    ,@SortCode varchar(4)
    ,@Notes varchar(2048)
    ,@IsActive tinyint
AS

INSERT ProductCategory (CategoryName
    ,SortCode
    ,Notes
    ,IsActive
    ,CreateDate, ModifyDate)
VALUES(@CategoryName
    ,@SortCode
    ,@Notes
    ,@IsActive
    ,GETDATE(),GETDATE())

SELECT @ProductCategoryId=@@IDENTITY

GO

GRANT EXECUTE ON dbo.InsertProductCategory TO Programs

GO

---------------

CREATE PROC dbo.UpdateProductCategory
    @ProductCategoryId int
    ,@CategoryName varchar(40)
    ,@SortCode varchar(4)
    ,@Notes varchar(2048)
    ,@IsActive tinyint
AS

UPDATE ProductCategory
    SET CategoryName=@CategoryName
    ,SortCode=@SortCode
    ,Notes=@Notes
    ,IsActive=@IsActive
    ,ModifyDate=GETDATE()
WHERE ProductCategoryId=@ProductCategoryId

GO

GRANT EXECUTE ON dbo.UpdateProductCategory TO Programs

GO

---------------

CREATE PROC dbo.DeleteProductCategory
  @ProductCategoryId int
AS

DELETE ProductCategory
WHERE  ProductCategoryId=@ProductCategoryId

GO

GRANT EXECUTE ON dbo.DeleteProductCategory TO Programs

GO

-- ProductSubCategory Stored Procedures

DROP PROC dbo.GetProductSubCategory
DROP PROC dbo.InsertProductSubCategory
DROP PROC dbo.UpdateProductSubCategory
DROP PROC dbo.DeleteProductSubCategory

GO

---------------

CREATE PROC dbo.GetProductSubCategory
  @ProductSubCategoryId int
AS

SELECT *
FROM   ProductSubCategory
WHERE  ProductSubCategoryId=@ProductSubCategoryId

GO

GRANT EXECUTE ON dbo.GetProductSubCategory TO Programs

GO

---------------

CREATE PROC dbo.InsertProductSubCategory
    @ProductSubCategoryId int out
    ,@SubCategoryName varchar(40)
    ,@SortCode varchar(6)
    ,@ProductCategoryId int
    ,@DefaultProfitMargin int
    ,@Notes varchar(2048)
    ,@IsActive tinyint
    ,@PricingRequiresReview tinyint
AS

INSERT ProductSubCategory (SubCategoryName
    ,SortCode
    ,ProductCategoryId
    ,DefaultProfitMargin
    ,Notes
    ,IsActive
    ,PricingRequiresReview
    ,CreateDate, ModifyDate)
VALUES(@SubCategoryName
    ,@SortCode
    ,@ProductCategoryId
    ,@DefaultProfitMargin
    ,@Notes
    ,@IsActive
    ,@PricingRequiresReview
    ,GETDATE(),GETDATE())

SELECT @ProductSubCategoryId=@@IDENTITY

GO

GRANT EXECUTE ON dbo.InsertProductSubCategory TO Programs

GO

---------------

CREATE PROC dbo.UpdateProductSubCategory
    @ProductSubCategoryId int
    ,@SubCategoryName varchar(40)
    ,@SortCode varchar(6)
    ,@ProductCategoryId int
    ,@DefaultProfitMargin int
    ,@Notes varchar(2048)
    ,@IsActive tinyint
    ,@PricingRequiresReview tinyint
AS

UPDATE ProductSubCategory
    SET SubCategoryName=@SubCategoryName
    ,SortCode=@SortCode
    ,ProductCategoryId=@ProductCategoryId
    ,DefaultProfitMargin=@DefaultProfitMargin
    ,Notes=@Notes
    ,IsActive=@IsActive
    ,PricingRequiresReview=@PricingRequiresReview
    ,ModifyDate=GETDATE()
WHERE ProductSubCategoryId=@ProductSubCategoryId

GO

GRANT EXECUTE ON dbo.UpdateProductSubCategory TO Programs

GO

---------------

CREATE PROC dbo.DeleteProductSubCategory
  @ProductSubCategoryId int
AS

DELETE ProductSubCategory
WHERE  ProductSubCategoryId=@ProductSubCategoryId

GO

GRANT EXECUTE ON dbo.DeleteProductSubCategory TO Programs

GO

-- ProductBrand Stored Procedures

DROP PROC dbo.GetProductBrand
DROP PROC dbo.InsertProductBrand
DROP PROC dbo.UpdateProductBrand
DROP PROC dbo.DeleteProductBrand

GO

---------------

CREATE PROC dbo.GetProductBrand
  @ProductBrandId int
AS

SELECT *
FROM   ProductBrand
WHERE  ProductBrandId=@ProductBrandId

GO

GRANT EXECUTE ON dbo.GetProductBrand TO Programs

GO

---------------

CREATE PROC dbo.InsertProductBrand
    @ProductBrandId int out
    ,@BrandName varchar(80)
    ,@Notes varchar(2048)
    ,@IsActive tinyint
AS

INSERT ProductBrand (BrandName
    ,Notes
    ,IsActive
    ,CreateDate, ModifyDate)
VALUES(@BrandName
    ,@Notes
    ,@IsActive
    ,GETDATE(),GETDATE())

SELECT @ProductBrandId=@@IDENTITY

GO

GRANT EXECUTE ON dbo.InsertProductBrand TO Programs

GO

---------------

CREATE PROC dbo.UpdateProductBrand
    @ProductBrandId int
    ,@BrandName varchar(80)
    ,@Notes varchar(2048)
    ,@IsActive tinyint
AS

UPDATE ProductBrand
    SET BrandName=@BrandName
    ,Notes=@Notes
    ,IsActive=@IsActive
    ,ModifyDate=GETDATE()
WHERE ProductBrandId=@ProductBrandId

GO

GRANT EXECUTE ON dbo.UpdateProductBrand TO Programs

GO

---------------

CREATE PROC dbo.DeleteProductBrand
  @ProductBrandId int
AS

DELETE ProductBrand
WHERE  ProductBrandId=@ProductBrandId

GO

GRANT EXECUTE ON dbo.DeleteProductBrand TO Programs

GO

-- Product Stored Procedures

DROP PROC dbo.GetProduct
DROP PROC dbo.InsertProduct
DROP PROC dbo.UpdateProduct
DROP PROC dbo.DeleteProduct

GO

---------------

CREATE PROC dbo.GetProduct
  @ProductId int
AS

SELECT *
FROM   Product
WHERE  ProductId=@ProductId

GO

GRANT EXECUTE ON dbo.GetProduct TO Programs

GO

---------------

CREATE PROC dbo.InsertProduct
    @ProductId int out
    ,@ProductName varchar(100)
    ,@ProductSubCategoryId int
    ,@Size varchar(30)
    ,@RetailPrice money
    ,@ProductBrandId int
    ,@ManufacturerBarcode varchar(30)
    ,@ManufacturerPartNum varchar(30)
    ,@IsActive tinyint
    ,@PricingRequiresReview tinyint
AS

INSERT Product (ProductName
    ,ProductSubCategoryId
    ,Size
    ,RetailPrice
    ,ProductBrandId
    ,ManufacturerBarcode
    ,ManufacturerPartNum
    ,IsActive
    ,PricingRequiresReview
    ,CreateDate, ModifyDate)
VALUES(@ProductName
    ,@ProductSubCategoryId
    ,@Size
    ,@RetailPrice
    ,@ProductBrandId
    ,@ManufacturerBarcode
    ,@ManufacturerPartNum
    ,@IsActive
    ,@PricingRequiresReview
    ,GETDATE(),GETDATE())

SELECT @ProductId=@@IDENTITY

GO

GRANT EXECUTE ON dbo.InsertProduct TO Programs

GO

---------------

CREATE PROC dbo.UpdateProduct
    @ProductId int
    ,@ProductName varchar(100)
    ,@ProductSubCategoryId int
    ,@Size varchar(30)
    ,@RetailPrice money
    ,@ProductBrandId int
    ,@ManufacturerBarcode varchar(30)
    ,@ManufacturerPartNum varchar(30)
    ,@IsActive tinyint
    ,@PricingRequiresReview tinyint
AS

UPDATE Product
    SET ProductName=@ProductName
    ,ProductSubCategoryId=@ProductSubCategoryId
    ,Size=@Size
    ,RetailPrice=@RetailPrice
    ,ProductBrandId=@ProductBrandId
    ,ManufacturerBarcode=@ManufacturerBarcode
    ,ManufacturerPartNum=@ManufacturerPartNum
    ,IsActive=@IsActive
    ,PricingRequiresReview=@PricingRequiresReview
    ,ModifyDate=GETDATE()
WHERE ProductId=@ProductId

GO

GRANT EXECUTE ON dbo.UpdateProduct TO Programs

GO

---------------

CREATE PROC dbo.DeleteProduct
  @ProductId int
AS

DELETE Product
WHERE  ProductId=@ProductId

GO

GRANT EXECUTE ON dbo.DeleteProduct TO Programs

GO

-- VendorProduct Stored Procedures

DROP PROC dbo.GetVendorProduct
DROP PROC dbo.InsertVendorProduct
DROP PROC dbo.UpdateVendorProduct
DROP PROC dbo.DeleteVendorProduct

GO

---------------

CREATE PROC dbo.GetVendorProduct
  @VendorProductId int
AS

SELECT *
FROM   VendorProduct
WHERE  VendorProductId=@VendorProductId

GO

GRANT EXECUTE ON dbo.GetVendorProduct TO Programs

GO

---------------

CREATE PROC dbo.InsertVendorProduct
    @VendorProductId int out
    ,@VendorId int
    ,@ProductId int
    ,@RetailPriceOverride money
    ,@VendorPartNum varchar(30)
    ,@CaseCost money
    ,@CountInCase int
    ,@EachCost money
    ,@PreferredSource tinyint
    ,@IsActive tinyint
    ,@PricingRequiresReview tinyint
    ,@NumAndCostRequireReview tinyint
AS

INSERT VendorProduct (VendorId
    ,ProductId
    ,RetailPriceOverride
    ,VendorPartNum
    ,CaseCost
    ,CountInCase
    ,EachCost
    ,PreferredSource
    ,IsActive
    ,PricingRequiresReview
    ,NumAndCostRequireReview
    ,CreateDate, ModifyDate)
VALUES(@VendorId
    ,@ProductId
    ,@RetailPriceOverride
    ,@VendorPartNum
    ,@CaseCost
    ,@CountInCase
    ,@EachCost
    ,@PreferredSource
    ,@IsActive
    ,@PricingRequiresReview
    ,@NumAndCostRequireReview
    ,GETDATE(),GETDATE())

SELECT @VendorProductId=@@IDENTITY

GO

GRANT EXECUTE ON dbo.InsertVendorProduct TO Programs

GO

---------------

CREATE PROC dbo.UpdateVendorProduct
    @VendorProductId int
    ,@VendorId int
    ,@ProductId int
    ,@RetailPriceOverride money
    ,@VendorPartNum varchar(30)
    ,@CaseCost money
    ,@CountInCase int
    ,@EachCost money
    ,@PreferredSource tinyint
    ,@IsActive tinyint
    ,@PricingRequiresReview tinyint
    ,@NumAndCostRequireReview tinyint
AS

UPDATE VendorProduct
    SET VendorId=@VendorId
    ,ProductId=@ProductId
    ,RetailPriceOverride=@RetailPriceOverride
    ,VendorPartNum=@VendorPartNum
    ,CaseCost=@CaseCost
    ,CountInCase=@CountInCase
    ,EachCost=@EachCost
    ,PreferredSource=@PreferredSource
    ,IsActive=@IsActive
    ,PricingRequiresReview=@PricingRequiresReview
    ,NumAndCostRequireReview=@NumAndCostRequireReview
    ,ModifyDate=GETDATE()
WHERE VendorProductId=@VendorProductId

GO

GRANT EXECUTE ON dbo.UpdateVendorProduct TO Programs

GO

---------------

CREATE PROC dbo.DeleteVendorProduct
  @VendorProductId int
AS

DELETE VendorProduct
WHERE  VendorProductId=@VendorProductId

GO

GRANT EXECUTE ON dbo.DeleteVendorProduct TO Programs

GO

-- PurOrder Stored Procedures

DROP PROC dbo.GetPurOrder
DROP PROC dbo.InsertPurOrder
DROP PROC dbo.UpdatePurOrder
DROP PROC dbo.DeletePurOrder

GO

---------------

CREATE PROC dbo.GetPurOrder
  @PurOrderId int
AS

SELECT *
FROM   PurOrder
WHERE  PurOrderId=@PurOrderId

GO

GRANT EXECUTE ON dbo.GetPurOrder TO Programs

GO

---------------

CREATE PROC dbo.InsertPurOrder
    @PurOrderId int out
    ,@VendorId int
    ,@OrderNumber varchar(12)
    ,@OrderDate smalldatetime
    ,@ShipDate smalldatetime
    ,@SubmitDate smalldatetime
    ,@CreatedBy varchar(20)
    ,@Discount int
    ,@InvoiceNumber varchar(12)
    ,@Freight money
    ,@Terms varchar(20)
    ,@Notes varchar(2048)
AS

INSERT PurOrder (VendorId
    ,OrderNumber
    ,OrderDate
    ,ShipDate
    ,SubmitDate
    ,CreatedBy
    ,Discount
    ,InvoiceNumber
    ,Freight
    ,Terms
    ,Notes
    ,CreateDate, ModifyDate)
VALUES(@VendorId
    ,@OrderNumber
    ,@OrderDate
    ,@ShipDate
    ,@SubmitDate
    ,@CreatedBy
    ,@Discount
    ,@InvoiceNumber
    ,@Freight
    ,@Terms
    ,@Notes
    ,GETDATE(),GETDATE())

SELECT @PurOrderId=@@IDENTITY

GO

GRANT EXECUTE ON dbo.InsertPurOrder TO Programs

GO

---------------

CREATE PROC dbo.UpdatePurOrder
    @PurOrderId int
    ,@VendorId int
    ,@OrderNumber varchar(12)
    ,@OrderDate smalldatetime
    ,@ShipDate smalldatetime
    ,@SubmitDate smalldatetime
    ,@CreatedBy varchar(20)
    ,@Discount int
    ,@InvoiceNumber varchar(12)
    ,@Freight money
    ,@Terms varchar(20)
    ,@Notes varchar(2048)
AS

UPDATE PurOrder
    SET VendorId=@VendorId
    ,OrderNumber=@OrderNumber
    ,OrderDate=@OrderDate
    ,ShipDate=@ShipDate
    ,SubmitDate=@SubmitDate
    ,CreatedBy=@CreatedBy
    ,Discount=@Discount
    ,InvoiceNumber=@InvoiceNumber
    ,Freight=@Freight
    ,Terms=@Terms
    ,Notes=@Notes
    ,ModifyDate=GETDATE()
WHERE PurOrderId=@PurOrderId

GO

GRANT EXECUTE ON dbo.UpdatePurOrder TO Programs

GO

---------------

CREATE PROC dbo.DeletePurOrder
  @PurOrderId int
AS

DELETE PurOrder
WHERE  PurOrderId=@PurOrderId

GO

GRANT EXECUTE ON dbo.DeletePurOrder TO Programs

GO

-- PurLine Stored Procedures

DROP PROC dbo.GetPurLine
DROP PROC dbo.InsertPurLine
DROP PROC dbo.UpdatePurLine
DROP PROC dbo.DeletePurLine

GO

---------------

CREATE PROC dbo.GetPurLine
  @PurLineId int
AS

SELECT *
FROM   PurLine
WHERE  PurLineId=@PurLineId

GO

GRANT EXECUTE ON dbo.GetPurLine TO Programs

GO

---------------

CREATE PROC dbo.InsertPurLine
    @PurLineId int out
    ,@PurOrderId int
    ,@VendorProductId int
    ,@CaseCostOverride money
    ,@EachCostOverride money
    ,@OrderedEaches tinyint
    ,@QtyOrdered int
    ,@QtyReceived int
    ,@QtyBackordered int
    ,@QtyDamaged int
    ,@QtyMissing int
    ,@QtyOnHand int
    ,@Notes varchar(80)
AS

INSERT PurLine (PurOrderId
    ,VendorProductId
    ,CaseCostOverride
    ,EachCostOverride
    ,OrderedEaches
    ,QtyOrdered
    ,QtyReceived
    ,QtyBackordered
    ,QtyDamaged
    ,QtyMissing
    ,QtyOnHand
    ,Notes
    ,CreateDate, ModifyDate)
VALUES(@PurOrderId
    ,@VendorProductId
    ,@CaseCostOverride
    ,@EachCostOverride
    ,@OrderedEaches
    ,@QtyOrdered
    ,@QtyReceived
    ,@QtyBackordered
    ,@QtyDamaged
    ,@QtyMissing
    ,@QtyOnHand
    ,@Notes
    ,GETDATE(),GETDATE())

SELECT @PurLineId=@@IDENTITY

GO

GRANT EXECUTE ON dbo.InsertPurLine TO Programs

GO

---------------

CREATE PROC dbo.UpdatePurLine
    @PurLineId int
    ,@PurOrderId int
    ,@VendorProductId int
    ,@CaseCostOverride money
    ,@EachCostOverride money
    ,@OrderedEaches tinyint
    ,@QtyOrdered int
    ,@QtyReceived int
    ,@QtyBackordered int
    ,@QtyDamaged int
    ,@QtyMissing int
    ,@QtyOnHand int
    ,@Notes varchar(80)
AS

UPDATE PurLine
    SET PurOrderId=@PurOrderId
    ,VendorProductId=@VendorProductId
    ,CaseCostOverride=@CaseCostOverride
    ,EachCostOverride=@EachCostOverride
    ,OrderedEaches=@OrderedEaches
    ,QtyOrdered=@QtyOrdered
    ,QtyReceived=@QtyReceived
    ,QtyBackordered=@QtyBackordered
    ,QtyDamaged=@QtyDamaged
    ,QtyMissing=@QtyMissing
    ,QtyOnHand=@QtyOnHand
    ,Notes=@Notes
    ,ModifyDate=GETDATE()
WHERE PurLineId=@PurLineId

GO

GRANT EXECUTE ON dbo.UpdatePurLine TO Programs

GO

---------------

CREATE PROC dbo.DeletePurLine
  @PurLineId int
AS

DELETE PurLine
WHERE  PurLineId=@PurLineId

GO

GRANT EXECUTE ON dbo.DeletePurLine TO Programs

GO

