using System;
using System.Collections.Generic;
using Willowsoft.WillowLib.Data.Entity;
using Willowsoft.WillowLib.Data.Misc;
using Willowsoft.Ordering.Core.Repositories;

namespace Willowsoft.Ordering.Core.Entities
{
    // Generated by TypeWrapperGenerator

    public partial class JoinPlToVpToProd : IPersistable
    {
        public JoinPlToVpToProd(PurLine innerPurLine, VendorProduct innerVendorProduct, Product innerProduct)
        {
            mInnerPurLine = innerPurLine;
            mInnerVendorProduct = innerVendorProduct;
            mInnerProduct = innerProduct;
        }
        public JoinPlToVpToProd()
        {
            mInnerPurLine = new PurLine();
            mInnerVendorProduct = new VendorProduct();
            mInnerProduct = new Product();
        }

        private PurLine mInnerPurLine;
        public PurLine InnerPurLine { get { return mInnerPurLine; } }

        private VendorProduct mInnerVendorProduct;
        public VendorProduct InnerVendorProduct { get { return mInnerVendorProduct; } }

        private Product mInnerProduct;
        public Product InnerProduct { get { return mInnerProduct; } }

        // PurLine properties

        public PurOrderId PurLine_PurOrderId
        {
            get { return mInnerPurLine.PurOrderId; }
            set { mInnerPurLine.PurOrderId = value; }
        }

        public VendorProductId PurLine_VendorProductId
        {
            get { return mInnerPurLine.VendorProductId; }
            set { mInnerPurLine.VendorProductId = value; }
        }

        public Decimal PurLine_CaseCostOverride
        {
            get { return mInnerPurLine.CaseCostOverride; }
            set { mInnerPurLine.CaseCostOverride = value; }
        }

        public Decimal PurLine_EachCostOverride
        {
            get { return mInnerPurLine.EachCostOverride; }
            set { mInnerPurLine.EachCostOverride = value; }
        }

        public Boolean PurLine_OrderedEaches
        {
            get { return mInnerPurLine.OrderedEaches; }
            set { mInnerPurLine.OrderedEaches = value; }
        }

        public Int32 PurLine_QtyOrdered
        {
            get { return mInnerPurLine.QtyOrdered; }
            set { mInnerPurLine.QtyOrdered = value; }
        }

        public Int32 PurLine_QtyReceived
        {
            get { return mInnerPurLine.QtyReceived; }
            set { mInnerPurLine.QtyReceived = value; }
        }

        public Int32 PurLine_QtyBackordered
        {
            get { return mInnerPurLine.QtyBackordered; }
            set { mInnerPurLine.QtyBackordered = value; }
        }

        public Int32 PurLine_QtyDamaged
        {
            get { return mInnerPurLine.QtyDamaged; }
            set { mInnerPurLine.QtyDamaged = value; }
        }

        public Int32 PurLine_QtyMissing
        {
            get { return mInnerPurLine.QtyMissing; }
            set { mInnerPurLine.QtyMissing = value; }
        }

        public Int32 PurLine_QtyOnHand
        {
            get { return mInnerPurLine.QtyOnHand; }
            set { mInnerPurLine.QtyOnHand = value; }
        }

        public String PurLine_Notes
        {
            get { return mInnerPurLine.Notes; }
            set { mInnerPurLine.Notes = value; }
        }

        public PurLineId PurLine_Id
        {
            get { return mInnerPurLine.Id; }
            set { mInnerPurLine.Id = value; }
        }

        public DateTime PurLine_CreateDate
        {
            get { return mInnerPurLine.CreateDate; }
            set { mInnerPurLine.CreateDate = value; }
        }

        public DateTime PurLine_ModifyDate
        {
            get { return mInnerPurLine.ModifyDate; }
            set { mInnerPurLine.ModifyDate = value; }
        }

        // VendorProduct properties

        public VendorId VendorProduct_VendorId
        {
            get { return mInnerVendorProduct.VendorId; }
            set { mInnerVendorProduct.VendorId = value; }
        }

        public ProductId VendorProduct_ProductId
        {
            get { return mInnerVendorProduct.ProductId; }
            set { mInnerVendorProduct.ProductId = value; }
        }

        public Decimal VendorProduct_RetailPriceOverride
        {
            get { return mInnerVendorProduct.RetailPriceOverride; }
            set { mInnerVendorProduct.RetailPriceOverride = value; }
        }

        public String VendorProduct_VendorPartNum
        {
            get { return mInnerVendorProduct.VendorPartNum; }
            set { mInnerVendorProduct.VendorPartNum = value; }
        }

        public Decimal VendorProduct_CaseCost
        {
            get { return mInnerVendorProduct.CaseCost; }
            set { mInnerVendorProduct.CaseCost = value; }
        }

        public Int32 VendorProduct_CountInCase
        {
            get { return mInnerVendorProduct.CountInCase; }
            set { mInnerVendorProduct.CountInCase = value; }
        }

        public Decimal VendorProduct_EachCost
        {
            get { return mInnerVendorProduct.EachCost; }
            set { mInnerVendorProduct.EachCost = value; }
        }

        public Boolean VendorProduct_PreferredSource
        {
            get { return mInnerVendorProduct.PreferredSource; }
            set { mInnerVendorProduct.PreferredSource = value; }
        }

        public Boolean VendorProduct_IsActive
        {
            get { return mInnerVendorProduct.IsActive; }
            set { mInnerVendorProduct.IsActive = value; }
        }

        public Boolean VendorProduct_PricingRequiresReview
        {
            get { return mInnerVendorProduct.PricingRequiresReview; }
            set { mInnerVendorProduct.PricingRequiresReview = value; }
        }

        public Boolean VendorProduct_NumAndCostRequireReview
        {
            get { return mInnerVendorProduct.NumAndCostRequireReview; }
            set { mInnerVendorProduct.NumAndCostRequireReview = value; }
        }

        public VendorProductId VendorProduct_Id
        {
            get { return mInnerVendorProduct.Id; }
            set { mInnerVendorProduct.Id = value; }
        }

        public DateTime VendorProduct_CreateDate
        {
            get { return mInnerVendorProduct.CreateDate; }
            set { mInnerVendorProduct.CreateDate = value; }
        }

        public DateTime VendorProduct_ModifyDate
        {
            get { return mInnerVendorProduct.ModifyDate; }
            set { mInnerVendorProduct.ModifyDate = value; }
        }

        // Product properties

        public String Product_ProductName
        {
            get { return mInnerProduct.ProductName; }
            set { mInnerProduct.ProductName = value; }
        }

        public ProductSubCategoryId Product_ProductSubCategoryId
        {
            get { return mInnerProduct.ProductSubCategoryId; }
            set { mInnerProduct.ProductSubCategoryId = value; }
        }

        public String Product_Size
        {
            get { return mInnerProduct.Size; }
            set { mInnerProduct.Size = value; }
        }

        public Decimal Product_RetailPrice
        {
            get { return mInnerProduct.RetailPrice; }
            set { mInnerProduct.RetailPrice = value; }
        }

        public ProductBrandId Product_ProductBrandId
        {
            get { return mInnerProduct.ProductBrandId; }
            set { mInnerProduct.ProductBrandId = value; }
        }

        public String Product_ManufacturerBarcode
        {
            get { return mInnerProduct.ManufacturerBarcode; }
            set { mInnerProduct.ManufacturerBarcode = value; }
        }

        public String Product_ManufacturerPartNum
        {
            get { return mInnerProduct.ManufacturerPartNum; }
            set { mInnerProduct.ManufacturerPartNum = value; }
        }

        public Boolean Product_IsActive
        {
            get { return mInnerProduct.IsActive; }
            set { mInnerProduct.IsActive = value; }
        }

        public Boolean Product_PricingRequiresReview
        {
            get { return mInnerProduct.PricingRequiresReview; }
            set { mInnerProduct.PricingRequiresReview = value; }
        }

        public ProductId Product_Id
        {
            get { return mInnerProduct.Id; }
            set { mInnerProduct.Id = value; }
        }

        public DateTime Product_CreateDate
        {
            get { return mInnerProduct.CreateDate; }
            set { mInnerProduct.CreateDate = value; }
        }

        public DateTime Product_ModifyDate
        {
            get { return mInnerProduct.ModifyDate; }
            set { mInnerProduct.ModifyDate = value; }
        }

        // IPersistable members

        public bool IsDirty
        {
            get
            {
                return mInnerPurLine.IsDirty
                    | mInnerVendorProduct.IsDirty
                    | mInnerProduct.IsDirty;
            }
            set
            {
                mInnerPurLine.IsDirty = value;
                mInnerVendorProduct.IsDirty = value;
                mInnerProduct.IsDirty = value;
            }
        }

        public bool IsDeleted
        {
            get
            {
                return mInnerPurLine.IsDeleted
                    | mInnerVendorProduct.IsDeleted
                    | mInnerProduct.IsDeleted;
            }
            set
            {
                mInnerPurLine.IsDeleted = value;
                mInnerVendorProduct.IsDeleted = value;
                mInnerProduct.IsDeleted = value;
            }
        }

        public bool IsPersisted
        {
            get
            {
                return mInnerPurLine.IsPersisted
                    | mInnerVendorProduct.IsPersisted
                    | mInnerProduct.IsPersisted;
            }
        }

        // You'll have to add your own Validate()...
    }

    public partial class JoinPlToVpToProd
    {
        private string mSubCategoryName;
        private string mBrandname;
        private PurOrder mOrder;

        public void SetExternalData(
            Dictionary<int, ProductSubCategory> subCategories,
            Dictionary<int, ProductBrand> brands,
            PurOrder order)
        {
            mSubCategoryName = subCategories[mInnerProduct.ProductSubCategoryId.Value].SubCategoryName;
            mBrandname = brands[mInnerProduct.ProductBrandId.Value].BrandName;
            mOrder = order;
        }

        public string SubCategoryName
        {
            get { return mSubCategoryName; }
        }

        public string BrandName
        {
            get { return mBrandname; }
        }

        public decimal ExtendedCost
        {
            get
            {
                if (PurLine_QtyOrdered == 0)
                    return 0m;
                else
                    return PurLine_QtyOrdered * CostPerUnitOrdered;
            }
        }

        public double NormalMargin
        {
            get
            {
                return VendorProduct.ComputeMargin(Product_RetailPrice, ActualEachCost, FreightPercent);
            }
        }

        public double VendorMargin
        {
            get
            {
                return VendorProduct.ComputeMargin(VendorProduct_RetailPriceOverride, ActualEachCost, FreightPercent);
            }
        }

        private decimal NominalCaseCost
        {
            get
            {
                if (PurLine_CaseCostOverride > 0m)
                    return PurLine_CaseCostOverride;
                else
                    return VendorProduct_CaseCost;
            }
        }

        private decimal NominalEachCost
        {
            get
            {
                if (PurLine_EachCostOverride > 0m)
                    return PurLine_EachCostOverride;
                else
                    return VendorProduct_EachCost;
            }
        }

        public decimal CostPerUnitOrdered
        {
            get
            {
                if (PurLine_OrderedEaches)
                    return NominalEachCost;
                else
                    return NominalCaseCost;
            }
        }

        private decimal EachCostFromCaseCost
        {
            get
            {
                if (VendorProduct_CountInCase == 0)
                    return 0m;
                return (decimal)((double)NominalCaseCost / VendorProduct_CountInCase);
            }
        }

        public decimal ActualEachCost
        {
            get
            {
                decimal cost;
                if (PurLine_OrderedEaches)
                {
                    cost = NominalEachCost;
                    if (cost == 0m)
                        cost = EachCostFromCaseCost;
                }
                else
                {
                    cost = EachCostFromCaseCost;
                    if (cost == 0m)
                        cost = NominalEachCost;
                }
                return cost;
            }
        }

        private double FreightPercent
        {
            get
            {
                decimal orderTotalWithoutFreight = mOrder.UnpersistedTotal - mOrder.Freight;
                if (orderTotalWithoutFreight == 0m)
                    return 0.0;
                else
                    return (double)(mOrder.Freight / orderTotalWithoutFreight);
            }
        }

        public string OrderingUnit
        {
            get
            {
                return PurLine_OrderedEaches ? "each" : "case/" + VendorProduct_CountInCase.ToString();
            }
        }

        public string NonBlankSize
        {
            get
            {
                return string.IsNullOrEmpty(Product_Size) ? "-" : Product_Size;
            }
        }

        public void Validate(ErrorList errors)
        {
            mInnerPurLine.Validate(errors);
            mInnerVendorProduct.Validate(errors);
            mInnerProduct.Validate(errors);
            if (PurLine_QtyOrdered > 0)
            {
                if (PurLine_OrderedEaches)
                {
                    if (VendorProduct_EachCost == 0m && PurLine_EachCostOverride == 0m)
                        errors.Add(new EntityValidationError("You may not order in eaches without an each cost"));
                }
                else
                {
                    if (VendorProduct_CaseCost == 0m && PurLine_CaseCostOverride == 0m)
                        errors.Add(new EntityValidationError("You may not order in cases without a case cost"));
                }
            }
        }

        public override string ToString()
        {
            return InnerPurLine.ToString() + " - " + 
                InnerVendorProduct.ToString() + " - " + 
                InnerProduct.ToString();
        }
    }

    /// <summary>
    /// An EntityBindingList<JoinPlToVpToProd> that delegates persistence
    /// operations to the PurLine repository.
    /// </summary>
    public class JoinPlToVpToProdBindingList : PersistedBindingList<JoinPlToVpToProd>
    {
        public JoinPlToVpToProdBindingList()
            : base(Ambient.DbSession)
        {
        }

        public static JoinPlToVpToProdBindingList GetOrderLines(
            PurOrderId orderId,
            List<ProductCategory> categories,
            Dictionary<int, ProductSubCategory> subCategories,
            Dictionary<int, ProductBrand> brands,
            out PurOrder order)
        {
            JoinPlToVpToProdBindingList venprodJoinList = new JoinPlToVpToProdBindingList();
            using (Ambient.DbSession.Activate())
            {
                order = OrderingRepositories.PurOrder.Get(orderId);

                // Create dictionaries of Product and VendorProduct for PurOrder.VendorId and
                // all product categories.
                Dictionary<int, Product> productDict = new Dictionary<int, Product>();
                Dictionary<int, VendorProduct> vendorProductDict = new Dictionary<int, VendorProduct>();
                foreach (ProductCategory cat in categories)
                {
                    List<VendorProduct> vendorProducts = OrderingRepositories.VendorProduct.Get(
                        order.VendorId, cat.Id);
                    foreach (VendorProduct vendorProduct in vendorProducts)
                    {
                        vendorProductDict.Add(vendorProduct.Id.Value, vendorProduct);
                    }
                    List<Product> products = OrderingRepositories.Product.Get(order.VendorId, cat.Id);
                    foreach (Product product in products)
                    {
                        productDict.Add(product.Id.Value, product);
                    }
                }

                // Construct a JoinPlToVpToProd for each PurLine in order.
                List<PurLine> purLines = OrderingRepositories.PurLine.Get(orderId);
                foreach (PurLine purLine in purLines)
                {
                    VendorProduct vendorProduct = vendorProductDict[purLine.VendorProductId.Value];
                    Product product = productDict[vendorProduct.ProductId.Value];
                    JoinPlToVpToProd join = new JoinPlToVpToProd(purLine, vendorProduct, product);
                    join.SetExternalData(subCategories, brands, order);
                    venprodJoinList.Add(join);
                }
            }
            return venprodJoinList;
        }

        protected override void Delete(JoinPlToVpToProd entity)
        {
            throw new InvalidOperationException();
        }

        protected override void Insert(JoinPlToVpToProd entity)
        {
            throw new InvalidOperationException();
        }

        protected override void Update(JoinPlToVpToProd entity)
        {
            OrderingRepositories.PurLine.Update(entity.InnerPurLine);
        }

        public override string EntityDisplayName
        {
            get { return "order line"; }
        }
    }
}
