// Generated by Willowsoft.WillowLib.CodeGen.ClassCreator at 5/24/2015 2:17:45 PM
using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Data.SqlClient;
using Willowsoft.WillowLib.Data.Entity;
using Willowsoft.WillowLib.Data.Sql;
using Willowsoft.Ordering.Core.Entities;

namespace Willowsoft.Ordering.Core.Entities
{
    [DebuggerStepThrough]
    public class ProductId : EntityId
    {
        public ProductId() { }
        public ProductId(int value) : base(value) { }
    }

    public partial class Product : Entity<ProductId>
    {
        #region Private property fields

        private string mProductName;
        private ProductSubCategoryId mProductSubCategoryId;
        private string mSize;
        private decimal mRetailPrice;
        private ProductBrandId mProductBrandId;
        private string mManufacturerBarcode;
        private string mManufacturerPartNum;
        private bool mIsActive;
        private bool mPricingRequiresReview;
        private bool mExceptionalRetailPrice;
        private bool mIsProductDeleted;
        private bool mMultipleVendors;
        private int mQtyBusyMin;
        private int mQtyBusyMax;
        private int mQtySlowMin;
        private int mQtySlowMax;
        private string mNotes;
        private decimal mRetailPrice2;
        private decimal mPrice2SizeMultiplier;

        #endregion

        #region Constructors

        [DebuggerStepThrough]
        public Product(ProductId Id_,
            string ProductName_,
            ProductSubCategoryId ProductSubCategoryId_,
            string Size_,
            decimal RetailPrice_,
            ProductBrandId ProductBrandId_,
            string ManufacturerBarcode_,
            string ManufacturerPartNum_,
            bool IsActive_,
            bool PricingRequiresReview_,
            bool ExceptionalRetailPrice_,
            bool IsProductDeleted_,
            bool MultipleVendors_,
            int QtyBusyMin_,
            int QtyBusyMax_,
            int QtySlowMin_,
            int QtySlowMax_,
            string Notes_,
            decimal RetailPrice2_,
            decimal Price2SizeMultiplier_,
            DateTime CreateDate_,
            DateTime ModifyDate_)
            : base(Id_, CreateDate_, ModifyDate_)
        {
            mProductName = ProductName_;
            mProductSubCategoryId = ProductSubCategoryId_;
            mSize = Size_;
            mRetailPrice = RetailPrice_;
            mProductBrandId = ProductBrandId_;
            mManufacturerBarcode = ManufacturerBarcode_;
            mManufacturerPartNum = ManufacturerPartNum_;
            mIsActive = IsActive_;
            mPricingRequiresReview = PricingRequiresReview_;
            mExceptionalRetailPrice = ExceptionalRetailPrice_;
            mIsProductDeleted = IsProductDeleted_;
            mMultipleVendors = MultipleVendors_;
            mQtyBusyMin = QtyBusyMin_;
            mQtyBusyMax = QtyBusyMax_;
            mQtySlowMin = QtySlowMin_;
            mQtySlowMax = QtySlowMax_;
            mNotes = Notes_;
            mRetailPrice2 = RetailPrice2_;
            mPrice2SizeMultiplier = Price2SizeMultiplier_;
        }

        [DebuggerStepThrough]
        public Product()
            : this(new ProductId(),
            string.Empty,
            new ProductSubCategoryId(),
            string.Empty,
            0m,
            new ProductBrandId(),
            string.Empty,
            string.Empty,
            true,
            false,
            false,
            false,
            false,
            0,
            0,
            0,
            0,
            string.Empty,
            0m,
            0m,
            DateTime.Now, DateTime.Now)
        {
        }

        #endregion

        #region Encapsulated fields

        public string ProductName
        {
            [DebuggerStepThrough]
            get { return mProductName; }
            [DebuggerStepThrough]
            set { PropertySet(ref mProductName, value); }
        }

        public ProductSubCategoryId ProductSubCategoryId
        {
            [DebuggerStepThrough]
            get { return mProductSubCategoryId; }
            [DebuggerStepThrough]
            set { PropertySet(ref mProductSubCategoryId, value); }
        }

        public string Size
        {
            [DebuggerStepThrough]
            get { return mSize; }
            [DebuggerStepThrough]
            set { PropertySet(ref mSize, value); }
        }

        public decimal RetailPrice
        {
            [DebuggerStepThrough]
            get { return mRetailPrice; }
            [DebuggerStepThrough]
            set { PropertySet(ref mRetailPrice, value); }
        }

        public ProductBrandId ProductBrandId
        {
            [DebuggerStepThrough]
            get { return mProductBrandId; }
            [DebuggerStepThrough]
            set { PropertySet(ref mProductBrandId, value); }
        }

        public string ManufacturerBarcode
        {
            [DebuggerStepThrough]
            get { return mManufacturerBarcode; }
            [DebuggerStepThrough]
            set { PropertySet(ref mManufacturerBarcode, value); }
        }

        public string ManufacturerPartNum
        {
            [DebuggerStepThrough]
            get { return mManufacturerPartNum; }
            [DebuggerStepThrough]
            set { PropertySet(ref mManufacturerPartNum, value); }
        }

        public bool IsActive
        {
            [DebuggerStepThrough]
            get { return mIsActive; }
            [DebuggerStepThrough]
            set { PropertySet(ref mIsActive, value); }
        }

        public bool PricingRequiresReview
        {
            [DebuggerStepThrough]
            get { return mPricingRequiresReview; }
            [DebuggerStepThrough]
            set { PropertySet(ref mPricingRequiresReview, value); }
        }

        public bool ExceptionalRetailPrice
        {
            [DebuggerStepThrough]
            get { return mExceptionalRetailPrice; }
            [DebuggerStepThrough]
            set { PropertySet(ref mExceptionalRetailPrice, value); }
        }

        public bool IsProductDeleted
        {
            [DebuggerStepThrough]
            get { return mIsProductDeleted; }
            [DebuggerStepThrough]
            set { PropertySet(ref mIsProductDeleted, value); }
        }

        public bool MultipleVendors
        {
            [DebuggerStepThrough]
            get { return mMultipleVendors; }
            [DebuggerStepThrough]
            set { PropertySet(ref mMultipleVendors, value); }
        }

        public int QtyBusyMin
        {
            [DebuggerStepThrough]
            get { return mQtyBusyMin; }
            [DebuggerStepThrough]
            set { PropertySet(ref mQtyBusyMin, value); }
        }

        public int QtyBusyMax
        {
            [DebuggerStepThrough]
            get { return mQtyBusyMax; }
            [DebuggerStepThrough]
            set { PropertySet(ref mQtyBusyMax, value); }
        }

        public int QtySlowMin
        {
            [DebuggerStepThrough]
            get { return mQtySlowMin; }
            [DebuggerStepThrough]
            set { PropertySet(ref mQtySlowMin, value); }
        }

        public int QtySlowMax
        {
            [DebuggerStepThrough]
            get { return mQtySlowMax; }
            [DebuggerStepThrough]
            set { PropertySet(ref mQtySlowMax, value); }
        }

        public string Notes
        {
            [DebuggerStepThrough]
            get { return mNotes; }
            [DebuggerStepThrough]
            set { PropertySet(ref mNotes, value); }
        }

        public decimal RetailPrice2
        {
            [DebuggerStepThrough]
            get { return mRetailPrice2; }
            [DebuggerStepThrough]
            set { PropertySet(ref mRetailPrice2, value); }
        }

        public decimal Price2SizeMultiplier
        {
            [DebuggerStepThrough]
            get { return mPrice2SizeMultiplier; }
            [DebuggerStepThrough]
            set { PropertySet(ref mPrice2SizeMultiplier, value); }
        }

        #endregion
    }
}

namespace Willowsoft.Ordering.Core.Repositories
{
    public partial class SqlProductRepository
        : SqlEntityRepository<Product, ProductId, OrderingDataSet.ProductRow>,
        IProductRepository
    {
        #region SqlEntityRepository Members

        [DebuggerStepThrough]
        protected override Product CreateEntity(OrderingDataSet.ProductRow dataRow)
        {
            Product entity = new Product(new ProductId(dataRow.ProductId),
                dataRow.ProductName,
                new ProductSubCategoryId(dataRow.ProductSubCategoryId),
                dataRow.Size,
                (decimal)dataRow.RetailPrice,
                new ProductBrandId(dataRow.ProductBrandId),
                dataRow.ManufacturerBarcode,
                dataRow.ManufacturerPartNum,
                dataRow.IsActive > 0 ? true : false,
                dataRow.PricingRequiresReview > 0 ? true : false,
                dataRow.ExceptionalRetailPrice > 0 ? true : false,
                dataRow.IsProductDeleted > 0 ? true : false,
                dataRow.MultipleVendors > 0 ? true : false,
                dataRow.QtyBusyMin,
                dataRow.QtyBusyMax,
                dataRow.QtySlowMin,
                dataRow.QtySlowMax,
                dataRow.Notes,
                (decimal)dataRow.RetailPrice2,
                (decimal)dataRow.Price2SizeMultiplier,
                dataRow.CreateDate, dataRow.ModifyDate);
            return entity;
        }

        [DebuggerStepThrough]
        public override List<Product> CreateEntities(SqlDataAdapter adapter)
        {
            OrderingDataSet dataSet = new OrderingDataSet();
            adapter.Fill(dataSet.Product);
            return CreateEntities(dataSet.Product);
        }

        [DebuggerStepThrough]
        protected override void AddInsertUpdateParams(SqlCommand cmd, Product entity)
        {
            SqlHelper.AddParamVarchar(cmd, "@ProductName", entity.ProductName ?? string.Empty);
            SqlHelper.AddParamInputId(cmd, "@ProductSubCategoryId", entity.ProductSubCategoryId.Value);
            SqlHelper.AddParamVarchar(cmd, "@Size", entity.Size ?? string.Empty);
            SqlHelper.AddParamMoney(cmd, "@RetailPrice", entity.RetailPrice);
            SqlHelper.AddParamInputId(cmd, "@ProductBrandId", entity.ProductBrandId.Value);
            SqlHelper.AddParamVarchar(cmd, "@ManufacturerBarcode", entity.ManufacturerBarcode ?? string.Empty);
            SqlHelper.AddParamVarchar(cmd, "@ManufacturerPartNum", entity.ManufacturerPartNum ?? string.Empty);
            SqlHelper.AddParamTinyint(cmd, "@IsActive", entity.IsActive);
            SqlHelper.AddParamTinyint(cmd, "@PricingRequiresReview", entity.PricingRequiresReview);
            SqlHelper.AddParamTinyint(cmd, "@ExceptionalRetailPrice", entity.ExceptionalRetailPrice);
            SqlHelper.AddParamTinyint(cmd, "@IsProductDeleted", entity.IsProductDeleted);
            SqlHelper.AddParamTinyint(cmd, "@MultipleVendors", entity.MultipleVendors);
            SqlHelper.AddParamInt(cmd, "@QtyBusyMin", entity.QtyBusyMin);
            SqlHelper.AddParamInt(cmd, "@QtyBusyMax", entity.QtyBusyMax);
            SqlHelper.AddParamInt(cmd, "@QtySlowMin", entity.QtySlowMin);
            SqlHelper.AddParamInt(cmd, "@QtySlowMax", entity.QtySlowMax);
            SqlHelper.AddParamVarchar(cmd, "@Notes", entity.Notes ?? string.Empty);
            SqlHelper.AddParamMoney(cmd, "@RetailPrice2", entity.RetailPrice2);
            SqlHelper.AddParamMoney(cmd, "@Price2SizeMultiplier", entity.Price2SizeMultiplier);
        }

        protected override string EntityName
        {
            [DebuggerStepThrough]
            get { return "Product"; }
        }

        #endregion
    }
}
